name: "ant-pr"
description: "A GitHub Action that celebrates small, atomic pull requests."
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  config-path:
    required: false
    default: ".ant-pr.yml"
  repo-token:
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
